### ISSUE TITLE
erase spaces when tabsize=auto

### ISSUE THREAD

**Issue by meritozh** [Microsoft/vscode-backspace#1]
When `tabsize="auto"`, if i enter **two** <kbd>tab</kbd>, editor will insert **eight** space. Then, i just want to delete **four** spaces by hitting <kbd>backspace</kbd> once, but it will delete **eight** spaces by effect of this extension.

**Comment by jrieken** [comment]
`tabSize='auto'` means the editor will guess the indentation based on the current document. Internally that guess becomes a number which this extension then uses - in your specific case the I seems to have guessed 8 so it sort of works as implemented
